DROP DATABASE IF EXISTS task_db;

CREATE DATABASE task_db;

\c task_db ;

DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS tasks CASCADE;
DROP TABLE IF EXISTS workerSkills CASCADE;
DROP TABLE IF EXISTS taskPhoto CASCADE;
DROP TABLE IF EXISTS skills CASCADE;
DROP TABLE IF EXISTS public.hibernate_sequence CASCADE;

CREATE TABLE users (
    id INTEGER PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    free VARCHAR(255) NOT NULL,
    street VARCHAR(255) NOT NULL, 
    city VARCHAR(255) NOT NULL, 
    st VARCHAR(255) NOT NULL,
    zip VARCHAR(255) NOT NULL,
    photo VARCHAR(255) NOT NULL,
    rate VARCHAR(255) NOT NULL
);

CREATE TABLE tasks (
    id INTEGER PRIMARY KEY,
    owner INTEGER NOT NULL,
    ownername VARCHAR(255) NOT NULL,
    owneremail VARCHAR(255) NOT NULL,
    kind VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    details VARCHAR(255) NOT NULL,
    skill1 VARCHAR(255) NOT NULL,
    skill2 VARCHAR(255) NOT NULL, 
    skill3 VARCHAR(255) NOT NULL, 
    hours INTEGER NOT NULL,
    worker INTEGER 
);

CREATE TABLE workerSkills (
    id INTEGER PRIMARY KEY,
    worker INTEGER NOT NULL,
    skill VARCHAR(255) NOT NULL
);

CREATE TABLE taskPhoto (
    id INTEGER PRIMARY KEY,
    worker INTEGER NOT NULL,
    task INTEGER NOT NULL,
    photo VARCHAR(511) NOT NULL
);

CREATE TABLE skills (
    id INTEGER PRIMARY KEY,
    skill VARCHAR(511) NOT NULL
);

CREATE SEQUENCE public.hibernate_sequence INCREMENT 1 START 1000 MINVALUE 1;

